// Package gga provides the Gentleman Guardian Angel component for biggz-ai.
// GGA is an external CLI tool for AI-powered pre-commit code reviews.
// This component configures GGA by writing its config file and rules template.
package gga

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"

	"github.com/biggs-100/biggz-ai/internal/filemerge"
)

// InjectionResult describes what files were written.
type InjectionResult struct {
	ConfigFile    string
	AgentsFile    string
	ConfigChanged bool
	AgentsChanged bool
}

// ConfigPath returns the GGA config file path.
func ConfigPath(homeDir string) string {
	if runtime.GOOS == "windows" {
		return filepath.Join(os.Getenv("APPDATA"), "gga", "config")
	}
	return filepath.Join(homeDir, ".config", "gga", "config")
}

// AgentsTemplatePath returns the GGA AGENTS.md path.
func AgentsTemplatePath(homeDir string) string {
	if runtime.GOOS == "windows" {
		return filepath.Join(os.Getenv("APPDATA"), "gga", "AGENTS.md")
	}
	return filepath.Join(homeDir, ".config", "gga", "AGENTS.md")
}

// BuildConfig generates the GGA config content as shell variables.
func BuildConfig(provider string) []byte {
	content := `# Gentleman Guardian Angel Configuration
# Generated by biggz-ai

PROVIDER="` + provider + `"
FILE_PATTERNS="*.ts,*.tsx,*.js,*.jsx,*.py,*.go,*.rs,*.java,*.rb,*.cs"
EXCLUDE_PATTERNS="*.test.*,*.spec.*,*.d.ts,dist/*,build/*,node_modules/*,vendor/*"
RULES_FILE="AGENTS.md"
STRICT_MODE="true"
TIMEOUT="300"
`
	return []byte(content)
}

// Inject writes the GGA config file and AGENTS.md template.
func Inject(homeDir string) (InjectionResult, error) {
	result := InjectionResult{
		ConfigFile: ConfigPath(homeDir),
		AgentsFile: AgentsTemplatePath(homeDir),
	}

	// Write config
	configDir := filepath.Dir(result.ConfigFile)
	if err := os.MkdirAll(configDir, 0755); err != nil {
		return result, fmt.Errorf("mkdir config: %w", err)
	}

	configContent := BuildConfig("opencode")
	wr, err := filemerge.WriteFileAtomic(result.ConfigFile, configContent, 0644)
	if err != nil {
		return result, fmt.Errorf("write config: %w", err)
	}
	result.ConfigChanged = wr.Changed

	// Write AGENTS.md rules template
	agentsContent := []byte(`# GGA Code Review Rules

## General Rules
- No hardcoded secrets, API keys, or tokens
- No "any" types (TypeScript)
- No empty catch blocks
- No code duplication — extract shared logic
- No console.log/print in production code

## Response Format
First line must be: STATUS: PASSED or STATUS: FAILED
Then list findings with severity and location.
`)
	wr2, err := filemerge.WriteFileAtomic(result.AgentsFile, agentsContent, 0644)
	if err != nil {
		return result, fmt.Errorf("write agents: %w", err)
	}
	result.AgentsChanged = wr2.Changed

	return result, nil
}

// PostInstallMessages returns guidance messages after install.
func PostInstallMessages() []string {
	return []string{
		"Run 'gga install' in any git project to activate.",
		"Copy ~/.config/gga/AGENTS.md to your project root as review rules.",
	}
}
